CREATE DATABASE [SistemaUsuarios]
GO
USE [SistemaUsuarios]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 7/11/2024 08:54:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	 UNIQUE,
	  LUSTERED 
(
	[id] ASTATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Escritores](
	[id] [int] IDENTITY(1,1) NOT NULL,
	  NOT NULL,
	  NULL,
	[fechaNacimiento] [date] NOT NULL,
	  NULL,
	[bi NULL,
PRIMA[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_RE_DUP_KEY = OFF, 
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
